version: '3.8'

services:
    web-ro:
        build:
            context: .
        environment:
            - language=ro
        ports:
            - "8080:8001"
    web-en:
        build:
            context: .
        environment:
            - language=en
        ports:
            - "8081:8001"
